### ISSUE TITLE
about fp16

### ISSUE THREAD

**Issue by menglinhan** [OpenXiangShan/YunSuan#104]
您好，我这里咨询一个关于fp16的问题，我看运算下面的矢量浮点运算里，已经包含了fp64，fp32以及fp16（fp16在rvv1.0中并未包括）。我的理解是fp16的实现主要是对yunsuan模块有影响（支持fp16的运算）。
对运算模块以外的影响如下：根据SEW的配置来选择所要执行的指令是fp16形式，fp32形式还是fp64形式，这个在code里体现为fp_format信号上。
也就是说如果某个系统使用该vector模块，编译fp64+fp32的版本，和fp64+fp32+fp16的版本在运算模块外仅需修改fp_format信号相关逻辑即可。
不知道上述理解是否正确？

**Comment by xiaofeibao-xjtu** [comment]
我们的rtl默认都是支持fp16的，不支持裁剪，我们将来会支持Zfh拓展，如果只用来算f32和f64也没问题。

**Comment by menglinhan** [comment]
就是说现在的标量不支持fp16，矢量支持fp16对吧，然后矢量fp16中的某些功能涉及标量fp16，运算可能会出问题，这样理解对吗？

**Comment by xiaofeibao-xjtu** [comment]
目前还没有支持Zfh拓展，标量和向量指令都不会译码出fp16的相关计算，向量功能单元本身支持fp16的计算。

**Comment by menglinhan** [comment]
就是说向量仅是运算单元支持fp16，但译码不支持，是这样吧？

**Comment by xiaofeibao-xjtu** [comment]
目前是的

**Comment by menglinhan** [comment]
好的，了解了，谢谢
