### ISSUE TITLE
a question about floatFMA 

### ISSUE THREAD

**Issue by menglinhan** [OpenXiangShan/YunSuan#140]
Hi 

我对下面的一个问题有点困惑：
FloatFMA中a*b与c进行加法运算时，截取c右移后的数据代码如下（丢弃低两位）：
  val rshift_result_temp_f64     = rshift_result_with_grs_f64.head(rshiftMaxF64-2)
然后对于a*b的进位结果处理如下（我理解是考虑减法运算是的补码操作）：
    Cat(U_CSAnto2.io.out_car.head(106), is_sub_f64_reg0 & !rshift_guard_f64 & !rshift_round_f64 & !rshift_sticky_f64),
而这里的rshift_guard_f64 对应的是rshift_result_with_grs_f64（2），已经在c的截取过程中被截走了，是不是判断 !rshift_round_f64 & !rshift_sticky_f64即可？

code file：/OpenXiangShan/YunSuan/tree/master/src/main/scala/yunsuan/fpu/FloatFMA.scala

**Comment by xiaofeibao-xjtu** [comment]
当Ec的指数在一个范围内rshift_round_f64=rshift_result_with_grs_f64(2)，否则它是0，这个条件去掉之后正不正确一眼看不出来，如果有兴趣你可以去掉并运行测试环境验证一下。

**Comment by xiaofeibao-xjtu** [comment]
看起来好像是的，guard位也参与了加法计算，那可能不需要再判断rshift_guard_f64了，不过不确定去掉之后有没有问题，需要验证才能确定。

**Comment by menglinhan** [comment]
还有一个疑惑的地方是这里，当rshift_value_f64.asSInt等于rshiftMaxF64.S时，rshift_result_with_grs_f64(0)为0，按照设计期望可能是希望进1。这些问题影响精度十分有限，我这边是看到了所以提问一下。
  val Ec_is_too_small_f64        = rshift_value_f64.asSInt > rshiftMaxF64.S
  val rshift_sticky_f64          = RegEnable(Mux(Ec_is_medium_f64, rshift_result_with_grs_f64(0), Mux(Ec_is_too_big_f64, 0.U, fp_c_significand_f64.orR)), fire)

**Comment by xiaofeibao-xjtu** [comment]
当rshift_value_f64.asSInt等于rshiftMaxF64.S时，Ec_is_too_small_f64和Ec_is_too_big_f64都是0，Ec_is_medium_f64=1，rshift_sticky_f64=rshift_result_with_grs_f64(0)，rshift_result_with_grs_f64(0)表示右移过程中的sticky位，不一定是0

**Comment by menglinhan** [comment]
这个我对齐了一下位数，以fp64为例，总位宽是53*3+4，初始时1.fc的53位占据高rshift_result_with_grs_f64的53位，右移rshiftMaxF64.S（53*3+4）时，所有1.fc部分正好全部移出rshift_result_with_grs_f64，因此rshift_result_with_grs_f64（0）是0,

**Comment by xiaofeibao-xjtu** [comment]
有没有看右移的这个方法shiftRightWithMuxSticky，不管移多少位，最低位始终是sticky

**Comment by menglinhan** [comment]
不好意思，之前看到了，后来忘记了，现在没什么问题了，多谢
