### ISSUE TITLE
关于RVV性能的讨论

### ISSUE THREAD

**Issue by zhongchengyong** [OpenXiangShan/YunSuan#78]
以下面这一段程序为例：
The function in C:

```
void vec_len(float *r, struct pt *v, int n){
  for (int i=0; i<n; ++i){
    struct pt p = v[i];
    r[i] = sqrtf(p.x*p.x + p.y*p.y + p.z*p.z);
  }
}
```
The function in RVV:

```
    # void vec_len_rvv(float *r, struct pt *pts, int n)

    #define r a0
    #define pts a1
    #define n a2
    #define vl a3
    #define Xs v0
    #define Ys v1
    #define Zs v2
    #define lens v3
    
    .globl vec_len_rvv
vec_len_rvv:
    vsetvli vl, n, e32
    vlseg3e32.v Xs, (pts) # loads interleaved Xs, Ys, Zs into 3 registers
    vfmul.vv lens, Xs, Xs
    vfmacc.vv lens, Ys, Ys
    vfmacc.vv lens, Zs, Zs
    vfsqrt.v lens, lens
    vse32.v lens, (r)
    sub n, n, vl
    sh2add r, vl, r # bump r ptr 4 bytes per float
    sh1add vl, vl, vl # multiply vl by 3 floats per point
    sh2add pts, vl, pts # bump v ptr 4 bytes per float (12 per pt)
    bnez n, vec_len_rvv
    ret
```
其中循环末尾从“sub”到"bnez"的标量指令一共有5条，假设是一个4发射的处理器，一次循环起码有1个cycle没有issue RVV指令(bubble)，这是否会导致RVV计算单元不能pipeline？如何从硬件架构上优化掉这1个cycle的bubble？

**Comment by huxuan0307** [comment]
假设我们只有一个向量部件，乘加指令是流水化的功能单元，开方指令使用不可流水的迭代功能单元。我们可以假定乘法需要3个周期执行完成，吞吐为1条指令/cycle，开方需要13个周期执行完成，吞吐为1/13条指令/cycle。在这个假设下画出时空图。你会发现，RVV计算单元的slots会被填得满满的，而标量指令会出现bubble。

**Comment by zhongchengyong** [comment]
> “sub”到"bnez"的标量指令一共有5条，假设是一个4发射的处理器，一次循环起码有1个cycle没有issue RVV指令(bubble)，这是否会导致RVV计算单元不能pipeline？如何从硬件架

感谢回复。还是没有理解，例如前面说的从sub到bnez这里有5条指令，也就是说这一拍肯定不能发射一条V指令，那乘加之间就会有bubble了？

**Comment by xiaofeibao-xjtu** [comment]
你可以画一下你理解的指令发射的时空图吗？

> > “sub”到"bnez"的标量指令一共有5条，假设是一个4发射的处理器，一次循环起码有1个cycle没有issue RVV指令(bubble)，这是否会导致RVV计算单元不能pipeline？如何从硬件架
> 
> 感谢回复。还是没有理解，例如前面说的从sub到bnez这里有5条指令，也就是说这一拍肯定不能发射一条V指令，那乘加之间就会有bubble了？
